export const STATES = {
  IDLE: 'IDLE',
  LISTENING: 'LISTENING',
  PROCESSING: 'PROCESSING',
  SPEAKING: 'SPEAKING',
  ERROR: 'ERROR',
};

export const TRANSITIONS = {
  [STATES.IDLE]: [STATES.LISTENING],
  [STATES.LISTENING]: [STATES.PROCESSING, STATES.IDLE],
  [STATES.PROCESSING]: [STATES.SPEAKING, STATES.ERROR, STATES.IDLE],
  [STATES.SPEAKING]: [STATES.IDLE, STATES.LISTENING],
  [STATES.ERROR]: [STATES.IDLE],
};

export function canTransition(from, to) {
  return TRANSITIONS[from]?.includes(to) ?? false;
}